[package]
name = "sip-cc"
version = "0.1.0"
edition = "2021"

[lib]
name = "sip_cc_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
xcap = "0.9"
gif = "0.14"
arboard = { version = "3.6", features = ["image-data"] }
rdev = "0.5"
image = "0.25"
dirs = "6"
rfd = "0.15"
chrono = "0.4"
open = "5"
